project:
  title: "dmgalicia.github.io"
  type: website
    twitter-card: true
  output-dir: docs
  
website:
  site-url: "dmgalicia.github.io"
  navbar:
    right:
      - href: index.qmd
        text: Inicio
      - href: CV.qmd
        text: CV
      - href: publications.qmd
        text: Publicaciones
      - href: presentations.qmd
        text: Presentaciones
      - href: blog.qmd
        text: Blog

format:
  html:
    theme: flatly